apiVersion: v1
kind: ConfigMap
metadata:
  name: url-shortener-config
  namespace: url-shortener
data:
  SERVICE_HOST: "0.0.0.0"
  SERVICE_PORT: "8080"
  MAX_RETRIES: "5"
  POSTGRES_HOST: "postgres-service.databases.svc.cluster.local"
  POSTGRES_PORT: "5432"
  POSTGRES_CONNECTION_POOL: "5"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  JWT_EXPIRE_ACCESS_TOKEN_SECONDS: "600"
  JWT_EXPIRE_REFRESH_TOKEN_SECONDS: "6000"
  JWT_VALIDATION_LEEWAY_SECONDS: "60"
  JWT_ENABLE_REVOKED_TOKENS: "false"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger.observability.svc.cluster.local:4317"
  # log level
  RUST_LOG: "info,opentelemetry_sdk=off"
