apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: api-gateway-secrets
  namespace: api-gateway
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: api-gateway-secrets
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: /dev/dev-k8s/url-shortener/postgres-user
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: /dev/dev-k8s/url-shortener/postgres-password
    - secretKey: JWT_SECRET
      remoteRef:
        key: /dev/dev-k8s/url-shortener/JWT_SECRET
