apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rabbitmq-secrets
  namespace: url-shortener
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: rabbitmq-secrets
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: /dev/dev-k8s/url-shortener/rabbitmq-username
    - secretKey: password
      remoteRef:
        key: /dev/dev-k8s/url-shortener/rabbitmq-password