apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: analytics-consumer-secrets
  namespace: url-shortener
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: analytics-consumer-secrets
    creationPolicy: Owner
  data:
    - secretKey: ANALYTICS_POSTGRES_USER
      remoteRef:
        key: /dev/dev-k8s/url-shortener/ANALYTICS_POSTGRES_USER
    - secretKey: ANALYTICS_POSTGRES_PASSWORD
      remoteRef:
        key: /dev/dev-k8s/url-shortener/ANALYTICS_POSTGRES_PASSWORD
