apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: url-shortener
  labels:
    app: url-shortener
    component: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: url-shortener
      component: jaeger
  template:
    metadata:
      labels:
        app: url-shortener
        component: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/jaeger:2.17.0
          ports:
            - containerPort: 16686
              name: ui
            - containerPort: 4317
              name: otlp-grpc
            - containerPort: 4318
              name: otlp-http
          imagePullPolicy: IfNotPresent
